name = "LeanCourse25"
version = "0.1.0"
keywords = ["math", "teaching"]
defaultTargets = ["LeanCourse25"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.style.longLine = true
weak.linter.unusedTactic = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.24.0"

[[lean_lib]]
name = "LeanCourse25"
